use soroban_sdk::contracterror;

// NOTE: Soroban's #[contracterror] XDR spec caps error enums at 50 cases
// (ScSpecUdtErrorEnumV0::cases is a VecM<_, 50>). This enum is already at
// that limit. If a new error code is ever needed, reuse a semantically-close
// existing variant instead of adding one rather than removing or renumbering
// an existing variant.
//
// NAMESPACE: hunty-core error codes occupy the range 1001–1999.
//   reward-manager uses 2001–2999 (see contracts/reward-manager/src/errors.rs).
//   nft-reward      uses 3001–3999 (see contracts/nft-reward/src/errors.rs).
// This guarantees that a numeric code read from a transaction envelope is
// unambiguous regardless of which contract frame produced it.
#[contracterror]
#[derive(Clone, Copy, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum HuntErrorCode {
    HuntNotFound = 1001,
    ClueNotFound = 1002,
    InvalidHuntStatus = 1003,
    PlayerNotRegistered = 1004,
    ClueAlreadyCompleted = 1005,
    InvalidAnswer = 1006,
    HuntNotActive = 1007,
    Unauthorized = 1008,
    InsufficientRewardPool = 1009,
    DuplicateRegistration = 1010,
    InvalidTitle = 1011,
    InvalidDescription = 1012,
    InvalidAddress = 1013,
    TooManyClues = 1014,
    InvalidQuestion = 1015,
    RefundFailed = 1016,
    NoCluesAdded = 1017,
    HuntNotCompleted = 1018,
    RewardAlreadyClaimed = 1019,
    /// A RewardManager cross-contract call failed. The originating contract's
    /// error code is published in the `reward_distribution_failed` diagnostic
    /// event emitted immediately before this error is returned, allowing
    /// off-chain clients to distinguish e.g. `InsufficientPool` (2002) from
    /// `Unauthorized` (2010) without needing per-upstream variants here.
    RewardDistributionFailed = 1020,
    NoRewardsConfigured = 1021,
    DuplicateSubmission = 1022,
    SubmissionExpired = 1023,
    BannedPlayer = 1024,
    NoRequiredClues = 1025,
    RateLimitExceeded = 1026,
    ScoreOverflow = 1027,
    RegistrationsPaused = 1028,
    AnswersPaused = 1029,
    RewardsPaused = 1030,
    HuntEndTimeInPast = 1031,
    NoPendingAdmin = 1032,
    PendingAdminMismatch = 1033,
    InvalidRarity = 1034,
    InvalidTimeBonusConfig = 1035,
    AddressBlacklisted = 1036,
    ContractPaused = 1037,
    InvalidMaxAttempts = 1038,
    InvalidWeight = 1039,
    HintNotAvailable = 1040,
    HintAlreadyUnlocked = 1041,
    InsufficientScore = 1042,
    TooManyCategories = 1043,
    InvalidCategory = 1044,
    InvalidDifficulty = 1045,
    CorruptPlayerProgress = 1046,
    HuntNotStarted = 1047,
    AdminAlreadyProposed = 1048,
    InvalidPoints = 1049,
    HuntFull = 1050,
}

#[derive(Debug)]
pub enum HuntError {
    HuntNotFound,
    ClueNotFound,
    InvalidHuntStatus,
    PlayerNotRegistered,
    ClueAlreadyCompleted,
    InvalidAnswer,
    HuntNotActive,
    Unauthorized,
    InsufficientRewardPool,
    DuplicateRegistration,
    InvalidTitle,
    InvalidDescription,
    InvalidAddress,
    TooManyClues,
    InvalidQuestion,
    RefundFailed,
    NoCluesAdded,
    HuntNotCompleted,
    RewardAlreadyClaimed,
    RewardDistributionFailed,
    NoRewardsConfigured,
    DuplicateSubmission,
    SubmissionExpired,
    BannedPlayer,
    NoRequiredClues,
    RateLimitExceeded,
    ScoreOverflow,
    RegistrationsPaused,
    AnswersPaused,
    RewardsPaused,
    HuntEndTimeInPast,
    NoPendingAdmin,
    PendingAdminMismatch,
    AdminAlreadyProposed,
    InvalidRarity,
    InvalidTimeBonusConfig,
    AddressBlacklisted,
    ContractPaused,
    InvalidMaxAttempts,
    InvalidWeight,
    HintNotAvailable,
    HintAlreadyUnlocked,
    InsufficientScore,
    TooManyCategories,
    InvalidCategory,
    InvalidDifficulty,
    CorruptPlayerProgress,
    HuntNotStarted,
    AttemptCooldownNotExpired,
}

impl From<HuntError> for HuntErrorCode {
    fn from(err: HuntError) -> Self {
        match err {
            HuntError::HuntNotFound => HuntErrorCode::HuntNotFound,
            HuntError::ClueNotFound => HuntErrorCode::ClueNotFound,
            HuntError::InvalidHuntStatus => HuntErrorCode::InvalidHuntStatus,
            HuntError::PlayerNotRegistered => HuntErrorCode::PlayerNotRegistered,
            HuntError::ClueAlreadyCompleted => HuntErrorCode::ClueAlreadyCompleted,
            HuntError::InvalidAnswer => HuntErrorCode::InvalidAnswer,
            HuntError::HuntNotActive => HuntErrorCode::HuntNotActive,
            HuntError::Unauthorized => HuntErrorCode::Unauthorized,
            HuntError::InsufficientRewardPool => HuntErrorCode::InsufficientRewardPool,
            HuntError::DuplicateRegistration => HuntErrorCode::DuplicateRegistration,
            HuntError::InvalidTitle => HuntErrorCode::InvalidTitle,
            HuntError::InvalidDescription => HuntErrorCode::InvalidDescription,
            HuntError::InvalidAddress => HuntErrorCode::InvalidAddress,
            HuntError::TooManyClues => HuntErrorCode::TooManyClues,
            HuntError::InvalidQuestion => HuntErrorCode::InvalidQuestion,
            HuntError::RefundFailed => HuntErrorCode::RefundFailed,
            HuntError::NoCluesAdded => HuntErrorCode::NoCluesAdded,
            HuntError::HuntNotCompleted => HuntErrorCode::HuntNotCompleted,
            HuntError::RewardAlreadyClaimed => HuntErrorCode::RewardAlreadyClaimed,
            HuntError::RewardDistributionFailed => HuntErrorCode::RewardDistributionFailed,
            HuntError::NoRewardsConfigured => HuntErrorCode::NoRewardsConfigured,
            HuntError::DuplicateSubmission => HuntErrorCode::DuplicateSubmission,
            HuntError::SubmissionExpired => HuntErrorCode::SubmissionExpired,
            HuntError::BannedPlayer => HuntErrorCode::BannedPlayer,
            HuntError::NoRequiredClues => HuntErrorCode::NoRequiredClues,
            HuntError::RateLimitExceeded => HuntErrorCode::RateLimitExceeded,
            HuntError::ScoreOverflow => HuntErrorCode::ScoreOverflow,
            HuntError::RegistrationsPaused => HuntErrorCode::RegistrationsPaused,
            HuntError::AnswersPaused => HuntErrorCode::AnswersPaused,
            HuntError::RewardsPaused => HuntErrorCode::RewardsPaused,
            HuntError::HuntEndTimeInPast => HuntErrorCode::HuntEndTimeInPast,
            HuntError::NoPendingAdmin => HuntErrorCode::NoPendingAdmin,
            HuntError::PendingAdminMismatch => HuntErrorCode::PendingAdminMismatch,
            HuntError::AdminAlreadyProposed => HuntErrorCode::AdminAlreadyProposed,
            HuntError::InvalidRarity => HuntErrorCode::InvalidRarity,
            HuntError::InvalidTimeBonusConfig => HuntErrorCode::InvalidTimeBonusConfig,
            HuntError::AddressBlacklisted => HuntErrorCode::AddressBlacklisted,
            HuntError::ContractPaused => HuntErrorCode::ContractPaused,
            HuntError::InvalidMaxAttempts => HuntErrorCode::InvalidMaxAttempts,
            HuntError::InvalidWeight => HuntErrorCode::InvalidWeight,
            HuntError::HintNotAvailable => HuntErrorCode::HintNotAvailable,
            HuntError::HintAlreadyUnlocked => HuntErrorCode::HintAlreadyUnlocked,
            HuntError::InsufficientScore => HuntErrorCode::InsufficientScore,
            HuntError::TooManyCategories => HuntErrorCode::TooManyCategories,
            HuntError::InvalidCategory => HuntErrorCode::InvalidCategory,
            HuntError::InvalidDifficulty => HuntErrorCode::InvalidDifficulty,
            HuntError::CorruptPlayerProgress => HuntErrorCode::CorruptPlayerProgress,
            HuntError::HuntNotStarted => HuntErrorCode::HuntNotStarted,
            HuntError::AttemptCooldownNotExpired => HuntErrorCode::RateLimitExceeded,
        }
    }
}
